server :
  #监听端口号
  port : :8080
mysql:
  #数据库用户名
  username     : root
  #数据库密码
  password     : root
  #主机地址
  host         : 127.0.0.1
  #数据库端口号
  port         : 3306
  #库名称
  database     : product
  #库字符集
  charset      : utf8mb4
  #空闲连接数
  MaxIdleConns : 10
  #最大连接数
  MaxOpenConns : 100

redis :
  #超时时间
  Timeout : 240
  #链接类型
  network : tcp
  #主机地址
  host: 123.206.201.139
  #数据库端口号
  port: 6379
  #密码
  password : 123456
  #空闲连接数
  MaxIdle: 10
  #最大连接数
  MaxActive: 100